%% RSA searchlight 
% 2. Estimate rank correation over suffled baseline
% by Alex Park 10.Oct.2018

close all
clear
clc
%% turn on the parallel computing
pflag = gcp('nocreate');
if isempty(pflag)
    poolsize=0;
else
    poolsize=pflag.NumWorkers;
end

%% Path setup
[ProjSet, fs, info, ROI, fname]=Call_default_PS;
[Subject, NSubject]=CallSubj_PS; % If the same subject, assign the same ID
BrRDM={'Mtv_FaceNMatch14', 'Mtv_AllFaces14'}; % Select the activity patterns generated by which model to generate RDM
% 'Mtv_FaceNMatch14' : 14 faces in the social hierarchy while downsampling
% the observations to match the number of samples
%'Mtv_AllFaces14' : 14 faces in the social hierarchy while including all
%responses
NPerm=info.Nperm; % number of permutation
[modelRDMs0, modelRDMsPerm]=EucRDM([2:15],NPerm); %generate model RDM (pairwise Euclidean Distances) and model RDMs from random suffles
modelRDMs=[{modelRDMs0}; modelRDMsPerm]';

%% Main
for md=1:numel(BrRDM)
    UsrOption.BhPath=fullfile(ProjSet.Respath, BrRDM{md}); 
    UsrOption.BrPath=[UsrOption.BhPath, fs, 'Vols', fs]; %Path where the generated RDMs are
    UsrOption.SvPath=[UsrOption.BhPath, fs, 'sL', fs]; %Save path
    if ~exist(UsrOption.SvPath, 'dir')
        mkdir(UsrOption.SvPath);
    end
    BrSUB = dir(fullfile(UsrOption.BrPath,['*', fname.RDMsearchligh])); % file info of RDMs generated from RSA_sL1_ExtractT
    for sbi=1:size(BrSUB,1) % NSub x NDays
        clear curSub
        curSub=BrSUB(sbi).name;
        if strcmp(BrSUB(sbi).name(1),info.prefix.day1)
            dayscan=1;
        else
            dayscan=2;
        end
        subj=BrSUB(sbi).name(2:4); % Subject ID (to combine differnt days's results)
        fprintf('%s   day:%d\n', subj, dayscan);
        [kendallT] = slctSubModel(curSub, modelRDMs, UsrOption);

        T0.Euc(sbi,:)=kendallT(1,:);
        B.Euc(sbi,:)=mean(kendallT(2:end,:)); %Baseline
        taua.(subj)(dayscan,:)=T0.Euc(sbi,:)-B.Euc(sbi,:); % Map Rank correation to each searchlight
    end
    
    % Find subject ID and average the taua across differnt days scan
    sublist=fieldnames(taua);
    for sj=1:NSubject
        si=find(ismember(Subject,sublist{sj}));
        T.Euc(si,:)=nanmean( taua.(sublist{sj}) );
    end    
    save(fullfile(UsrOption.BrPath, fname.RSAsl), 'T', 'B');
    
    delete(gcp('nocreate'));
end

%% Sub-functions
function [CorrT, CorrTr] = slctSubModel(curSub, modelRDMs_cell_orth, UsrOption)  
    %compute taua distribution (a model + NPerm)
    parfor mdi=1:size(modelRDMs_cell_orth,2)
        curRDM=modelRDMs_cell_orth{mdi};
        [taua] = appRSA(curSub, curRDM, UsrOption);
        CorrT(mdi,:) = taua';
    end
end

function [taua] = appRSA(sub, rdm, usroption)
    curROI=load([usroption.BrPath, sub]); %Series of RDM (NumSerchlight) generated from RSA_sL1_ExtractT
    RDMs=curROI.RDMs;    
    parfor vi=1:size(RDMs,2) % number of voxels (NumSerchlight)
        taua(vi)=rsa.stat.rankCorr_Kendall_taua( selectriu(RDMs(vi).RDMeuc),  selectriu(rdm) ); 
    end
end
